_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}
min_epochs: 1
max_epochs: 100
accelerator: gpu
devices: 1
precision: 16
enable_checkpointing: true
enable_progress_bar: true
enable_model_summary: true
check_val_every_n_epoch: 1
log_every_n_steps: 10
fast_dev_run: false  # 添加这个参数