# configs/model/adjustable_convlstm.yaml
_target_: src.models.adjustable_convlstm_module.AdjustableConvLSTM

# 基础架构参数
input_channels: 1
hidden_dims: [32, 64]  # 可以调整为 [16], [32], [32, 64, 128], [64, 128, 256]
kernel_sizes: [3, 3]   # 可以调整为 [3], [5], [3, 5, 7]
# num_layers: 3        # 如果设置了这个，会自动生成递增的hidden_dims

# 序列参数
input_frames: 5
output_frames: 3

# 正则化参数
dropout: 0.1
normalization: "group"  # 'none', 'batch', 'layer', 'group'

# 增强功能
use_attention: true
use_residual: true
use_skip_connections: true
activation: "tanh"  # 'tanh', 'relu', 'gelu'

# 解码策略
decoder_type: "autoregressive"  # 'autoregressive', 'teacher_forcing', 'scheduled'
teacher_forcing_ratio: 0.5

# 损失函数
loss_type: "combined"  # 'mse', 'mae', 'huber', 'combined'
loss_weights: [1.0, 1.2, 1.5]  # 对后面帧的预测给更高权重

# 优化参数
learning_rate: 0.001
weight_decay: 1e-5
compile: false